/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs2263;
import java.io.IOException;
import java.util.*;

import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.control.Button;
import javafx.scene.text.Text;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.geometry.Pos;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.input.MouseEvent;
public class App extends Application {
   
    
    
    @Override
    public void start(Stage primaryStage) throws Exception {
        IOManager IO = new IOManager();
        List<Student> studentData = IO.readData("studentdata.txt");

        primaryStage.setTitle("Course View");
        Label studentLabel = new Label("Students");
        Label coursesLabel = new Label("Courses");
        
        Text isTaking = new Text("Is Taking");
        isTaking.setStyle("-fx-border-style: segments(10,15,15,15) line-cap round");
        

        ListView studentList = new ListView();

        VBox leftBox = new VBox(studentLabel, studentList);
        leftBox.setAlignment(Pos.TOP_LEFT);
        //leftBox.setStyle("-fx-border-style: segments(10,15,15,15) line-cap round");
        leftBox.prefWidthProperty().bind(primaryStage.widthProperty().multiply(0.80));


        ListView courseList = new ListView();

        VBox rightBox = new VBox(coursesLabel, courseList);
        rightBox.setAlignment(Pos.TOP_LEFT);
        //rightBox.setStyle("-fx-border-style: segments(10,15,15,15) line-cap round");
        rightBox.prefWidthProperty().bind(primaryStage.widthProperty().subtract(10));

        Button loadButton = new Button("Load Data");

        loadButton.setOnAction(new EventHandler<ActionEvent>()  {
            @Override
            public void handle(ActionEvent actionEvent) {
                studentList.getItems().clear();
                for(Student student : studentData){
                studentList.getItems().add(student.toString());
                }
            }
        });

        
        studentList.setOnMouseClicked(new EventHandler<MouseEvent>(){
            @Override
            public void handle(MouseEvent arg0){
                for(Student student : studentData){
                    if (studentList.getSelectionModel().getSelectedItem().toString().equals(student.toString())){
                        courseList.getItems().clear();
                        List<Course> courses = student.getCourses();
                        for(Course course : courses){
                            courseList.getItems().add(course.toString());
                        }
                    }
                }
            }
        });
        

        HBox buttonBox = new HBox(loadButton);
        buttonBox.setAlignment(Pos.BOTTOM_RIGHT);

        HBox contentBox = new HBox(leftBox,isTaking,rightBox);
        contentBox.setAlignment(Pos.CENTER);

        VBox mainBox = new VBox(contentBox, buttonBox);
        
        mainBox.setAlignment(Pos.CENTER);

        

        Scene scene = new Scene(mainBox, 800, 400);

        primaryStage.setScene(scene);


        primaryStage.show();
    }
    

    public static void main(String[] args) {
        Application.launch(args);
    }
}
